person:
  name: Kevin_id${random.uuid}
  age: ${random.int}
  happy: true
  birth: 1992/05/06
  maps: {
      k1: v1, 
      k2: v2
    }
  lists: 
    - music
    - game
    - food
  dog: {
    name: DD,
    age: 3
  }
    